quizz/urls.py
from django.urls import include, path

from .views.public.quizzes import QuizzView, CreateQuizzView, UserQuizzesListView
from .views.public.pages import LegalView

from .views.management.data_import import QuestionsImportView, UndoImportView
from .views.management.questions import (
    QuestionsListView,
    EditQuestionView,
    QuestionDeleteView,
)
from .views.management.quizzes import QuizzesListView
from .views.management.tags import MigrateTagsView
from .views.management.users import UsersListView, UserProfileView


app_name = "quizz"

# fmt: off
management_patterns = (
    [
        path("questions", QuestionsListView.as_view(), name="questions"),
        path("questions/create", EditQuestionView.as_view(), name="questions-create"),
        path("questions/import", QuestionsImportView.as_view(), name="questions-import"),
        path("questions/import/undo", UndoImportView.as_view(), name="questions-import-undo",),
        path("questions/edit/<int:pk>", EditQuestionView.as_view(), name="questions-edit"),
        path("questions/delete/<int:pk>",QuestionDeleteView.as_view(), name="questions-delete",),
        path("quizzes", QuizzesListView.as_view(), name="quizzes"),
        path("quizzes/<str:username>", UserProfileView.as_view(), name="users-quizzes"),
        path("users", UsersListView.as_view(), name="users"),
        path("tags-migration", MigrateTagsView.as_view(), name="tags-migration"),
    ],
    "management",
)

urlpatterns = [
    path("", CreateQuizzView.as_view(), name="create-quizz"),
    path("quizzes", UserQuizzesListView.as_view(), name="user-quizzes"),
    path("quizz/<slug:slug>", QuizzView.as_view(), name="quizz"),
    path("legal", LegalView.as_view(), name="legal"),
    path("management/", include(management_patterns, namespace="management")),
]
# fmt: on

quizz/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext_lazy as _

from mptt.models import MPTTModel, TreeForeignKey, TreeManyToManyField
from uuslug import uuslug
from versatileimagefield.fields import VersatileImageField


class QuestionLocale(models.Model):
    """
    Questions are separated by locale.
    """

    """The ISO language tag for this locale (e.g. “fr_FR”)."""
    code = models.CharField(_("ISO code"), max_length=8)

    """The display name for this locale (e.g. “Français”)."""
    name = models.CharField(_("Display name"), max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ("name",)


class Contest(models.Model):
    """
    Questions can be from an existing contest.
    """

    name = models.CharField(_("Contest name"), max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ("name",)


class Tag(MPTTModel):
    """
    Tags are used to categorize questions: users can ask for questions
    with a specific tag only. Tags are hierarchical: if one ask for
    a tag, all questions with this tag or any child tag will be selected.
    """

    """The name of a tag, displayed to the end users."""
    name = models.CharField("Name of the tag", max_length=128)

    """The slug of a tag, for URLs."""
    slug = models.SlugField(editable=False)

    """
    In the tags hierarchy, this is the parent of this tag.
    """
    parent = TreeForeignKey(
        "self", on_delete=models.CASCADE, blank=True, null=True, related_name="children"
    )

    def save(self, *args, **kwargs):
        """Persists a tag, recalculating its slug."""
        self.slug = uuslug(self.name, instance=self)
        super(Tag, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    class MPTTMeta:
        order_insertion_by = ["name"]


class Answer(models.Model):
    """
    An answer to a question. Questions can either be multiple-choice,
    single-choice, free text or with linked answers; this represents
    all the cases.

    For multiple-choice questions, the Question will contain a list of
    answers, some marked as correct (using self.is_correct), some as incorrect.
    The user will have to select all correct answers, and only them.

    For linked answers questions, the Question will contain two lists: the
    list of answers, and the list of related answers. The user will have to link
    all answers correctly. The answers in the first list will have the
    self.correct_linked_answer field pointing to the correct answer. The other's
    and both self.is_correct fields are not relevant in this case.
    """

    """The answer's text displayed to the user, to be selected if correct."""
    answer = models.CharField(max_length=256)

    """True if this answer is correct."""
    is_correct = models.BooleanField()

    """
    The correct related answer. If this is set, the answer will be correct if
    linked to this other answer.
    """
    linked_answer = models.OneToOneField(
        "Answer",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name="linked_answer_reverse",
    )

    """
    True if this answer was deleted.
    Because quizz results reference answers, if an answer is deleted, it cannot
    be removed from the database. So, quizz results reference the questions and
    the answers that were active when the quizz was passed. Quizz will only display
    for new questions non-deleted answers.
    """
    is_deleted = models.BooleanField(default=False)

    @property
    def primary(self):
        return (
            not hasattr(self, "linked_answer_reverse") or not self.linked_answer_reverse
        )

    def __str__(self):
        return (
            ("[DELETED] " if self.is_deleted else "")
            + self.answer
            + (" (correct)" if self.is_correct else "")
        )


QUESTION_OPEN = "OPEN"
QUESTION_MCQ = "MCQ"
QUESTION_LINKED = "LINKED"

QUESTION_TYPES = (
    (QUESTION_OPEN, _("Open answer")),
    (QUESTION_MCQ, _("Multiple choices")),
    (QUESTION_LINKED, _("Linked answers")),
)


class Question(models.Model):
    """
    A question.

    Questions can either be:

     - open answer, without choices to select: the `answers` is empty
       as well as the `linked_answers`; the correct answer is in
       `open_valid_answer`;

     - multiple choices (MCQ): `answers` contains the choices (their
       correctness is stored into the answers); if `has_open_choice` is True,
       an “Other Answer” field will be displayed and matched against
       `open_valid_answer` (if this one is None, the answer will not be in the
       other input, but it will still be displayed);

     - linked choices: `answers` contains the choices; the answers reference
       their linked answer inside their model (using a self-one-to-one relation).
    """

    """The question's type"""
    type = models.CharField(
        verbose_name=_("Question's type"), choices=QUESTION_TYPES, max_length=6
    )

    """The question's locale"""
    locale = models.ForeignKey(
        QuestionLocale, on_delete=models.PROTECT, verbose_name=_("Locale"), max_length=8
    )

    """Some questions are extracted from a contest."""
    source = models.ForeignKey(
        Contest,
        on_delete=models.SET_NULL,
        verbose_name=_("Contest from which this question is taken"),
        blank=True,
        null=True,
    )

    """The question's difficulty, between 1 (easy) and 3 (hard)"""
    difficulty = models.PositiveSmallIntegerField(
        verbose_name=_("Difficulty"), default=1
    )

    """The question's tags."""
    tags = TreeManyToManyField(Tag, related_name="questions", verbose_name=_("Tags"))

    """The user who created or imported the question."""
    creator = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        verbose_name=_("Creator"),
        editable=False,
        blank=True,
        null=True,
        related_name="questions_created",
    )

    """The user(s) who edited the question."""
    editors = models.ManyToManyField(
        User, verbose_name=_("Editors"), editable=False, related_name="questions_edited"
    )

    """True if this question was imported."""
    imported = models.BooleanField(
        verbose_name=_("Was this question imported?"), editable=False, default=False
    )

    """The question's text."""
    question = models.CharField(verbose_name=_("Question"), max_length=256)

    """The question's illustration, if any."""
    illustration = VersatileImageField(
        verbose_name=_("Illustration"),
        null=True,
        blank=True,
        upload_to="quizz/illustrations/",
    )

    """True if we should add a “other” input after the proposed choices."""
    has_open_choice = models.BooleanField(
        verbose_name=_("Has open choice"), default=False
    )

    """For MCQ and linked choices, the choices."""
    answers = models.ManyToManyField(
        Answer, verbose_name=_("Question's proposed answers"), related_name="questions"
    )

    """
    For open answers ans MCQ with open answer, the correct open answer.
    For MCQ with open answer, if None, the “Other” input will be displayed but
    have to be left empty.
    """
    open_valid_answer = models.CharField(
        verbose_name=_(
            "Question's valid answer if this is an open question or if this is a MCQ and the answer is not in the "
            "proposed answers"
        ),
        blank=True,
        null=True,
        default=None,
        max_length=1024,
    )

    """In the correction phase, will allow to display an extra explanation."""
    answer_comment = models.TextField(
        verbose_name=_("Answer's comment"), max_length=2 ** 16, blank=True, null=True
    )

    def __str__(self):
        return f"{self.question} ({self.verbose_type})"

    @property
    def verbose_type(self):
        for question_type, verbose in QUESTION_TYPES:
            if self.type == question_type:
                return verbose
        return "UNKNOWN"  # Only for non-filled & unsaved questions

    @property
    def selectable_answers(self):
        """
        Returns the selectable answers of this question.

        If this question is an open question, returns None.
        If it is a MCQ, returns a list of answers.
        If it is a linked question, returns a list of tuples of answers linked
        together.
        :return: The answers.
        """
        if self.type == "OPEN":
            return None
        elif self.type == "MCQ":
            return self.answers.filter(is_deleted=False)
        elif self.type == "LINKED":
            return [
                (answer.answer, answer.linked_answer.answer)
                for answer in self.answers.filter(is_deleted=False)
                if answer.answer and answer.linked_answer.answer
            ]

    @property
    def answers_count(self):
        return self.answers.filter(is_deleted=False).count()

    @property
    def reduced_tags(self):
        """
        Reduces the tags to a minimal set, for display.

        If there is a tag and all its children, the children are omitted.
        Also, for each tag we check all ancestors; if there are ancestors in
        the tags list, they are removed as they will be implied anyway.

        :return: A dictionary {tag_pk: (tag, number of children omitted)}
        """
        tags = self.tags.all()
        reduced = {tag.pk: (tag, 1) for tag in tags}

        tag: Tag
        for tag in tags:
            if tag.is_leaf_node():
                continue

            descendants = tag.get_descendants()
            all_in = True
            for child in descendants:
                all_in &= child in tags

            if all_in:
                reduced[tag.pk] = tag, tag.get_descendant_count()
                for child in tag.get_descendants():

quizz/forms/public.py
from django import forms
from django.utils.translation import gettext_lazy as _

from quizz.fields import TreeNodeAllMultipleChoiceField
from quizz.models import Tag, QuestionLocale, Contest
from quizz.widgets import CheckboxTreeSelectMultiple


class CreateQuizzForm(forms.Form):
    how_many = forms.IntegerField(
        label=_("How many questions?"),
        min_value=1,
        max_value=100,
        initial=10,
        widget=forms.NumberInput(attrs={"class": "input is-inline is-medium"}),
    )

    tags = TreeNodeAllMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=CheckboxTreeSelectMultiple(
            container_classes="columns is-multiline",
            columns_classes="column is-6",
            bold_parents=True,
            attrs={"class": "checkbox"},
        ),
        required=False,
    )

    difficulty = forms.ChoiceField(
        label=_("Difficulty"),
        choices=(
            (0, _("Indifferent")),
            (1, _("Easy")),
            (2, _("Medium")),
            (3, _("Hard")),
        ),
        required=False,
        initial=0,
        widget=forms.RadioSelect,
    )

    locale = forms.ModelChoiceField(
        label=_("Language"),
        queryset=QuestionLocale.objects.all(),
        required=False,
        empty_label=_("Indifferent"),
        widget=forms.RadioSelect,
    )

    contest = forms.ModelChoiceField(
        label=_("Pick questions from"),
        queryset=Contest.objects.all(),
        required=False,
        empty_label=_("All contests, plus exclusive training questions"),
    )

quizz/forms/quizzes.py
import random
from django import forms
from django.utils.translation import gettext_lazy as _

from quizz.models import QUESTION_OPEN, QUESTION_MCQ, QUESTION_LINKED


class QuestionForm(forms.Form):
    def __init__(self, question, **kwargs):
        super().__init__(**kwargs)
        self.question = question


class OpenQuestionForm(QuestionForm):
    def __init__(self, question, **kwargs):
        super().__init__(question, **kwargs)
        assert self.question.type == QUESTION_OPEN, (
            "Trying to use OpenQuestionForm with a question of type %s"
            % self.question.type
        )

    answer = forms.CharField(
        label=_("Your answer"),
        required=False,
        widget=forms.Textarea(
            attrs={
                "rows": 3,
                "resizable": "y",
                "placeholder": _("Type your answer here…"),
                "class": "textarea",
            }
        ),
    )


class MultipleChoicesQuestionForm(QuestionForm):
    def __init__(self, question, **kwargs):
        super().__init__(question, **kwargs)

        assert self.question.type == QUESTION_MCQ, (
            "Trying to use MultipleChoicesQuestionForm with a question of type %s"
            % self.question.type
        )

        choices = [
            (answer.pk, answer.answer) for answer in self.question.selectable_answers
        ]
        random.shuffle(choices)

        self.fields["answers"] = forms.MultipleChoiceField(
            label=_("Select all valid answers"),
            choices=choices,
            required=False,
            widget=forms.CheckboxSelectMultiple,
        )

        if question.has_open_choice:
            self.fields["other_answer"] = forms.CharField(
                label=_("Other"),
                required=False,
                widget=forms.TextInput(
                    attrs={"class": "input", "placeholder": _("Write the answer here…")}
                ),
                help_text=_(
                    "If none of the above choices are correct, or if there is "
                    "another answer, write it here. Otherwise, leave this "
                    "field blank. Punctuation, capitalization, accents, "
                    "diatrics, spaces or line breaks does not matter."
                ),
            )


class LinkedQuestionForm(QuestionForm):
    def __init__(self, question, **kwargs):
        super().__init__(question, **kwargs)

        assert self.question.type == QUESTION_LINKED, (
            "Trying to use LinkedQuestionForm with a question of type %s"
            % self.question.type
        )

        answers = self.question.selectable_answers_with_pk
        linked_answers = [(answer[1][0], answer[1][1]) for answer in answers]

        random.shuffle(answers)
        random.shuffle(linked_answers)

        for answer in answers:
            self.fields[f"{answer[0][0]}"] = forms.ChoiceField(
                label=answer[0][1], choices=linked_answers, required=True
            )

quizz/templates/snippets/flash-messages.html
{% if messages %}
    <section class="section">
        <div class="container">
            {% for message in messages %}
                <article class="message {% spaceless %}
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.DEBUG %}is-link
                    {% elif message.level == DEFAULT_MESSAGE_LEVELS.INFO %}is-info
                    {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}is-success
                    {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}is-warning
                    {% elif message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}is-danger
                    {% endif %}
                {% endspaceless %} {% if message.tags %}{{ message.tags }}{% endif %}">
                    <div class="message-body">
                        <span>{{ message }}</span>
                        <button class="delete" aria-label="delete"></button>
                    </div>
                </article>
            {% endfor %}
        </div>
    </section>
{% endif %}

quizz/templates/snippets/question-card.html
{% load i18n %}
{% load mathfilters %}
{% load mptt_tags %}

<div class="card">
    <div class="card-content">
        <div class="media">
            {% if question.illustration %}
                <div class="media-left">
                    <figure class="image is-48x48">
                        <img src="{{ question.illustration.thumbnail.96x96 }}" alt="{% trans "Question's illustration" %}">
                    </figure>
                </div>
            {% endif %}
            <div class="media-content">
                <p class="title is-4">{{ question.question }}</p>
                <p class="subtitle is-6">
                    {% spaceless %}
                        {% if question.type != "OPEN" %}
                            {{ question.answers_count }} {{ question.verbose_type|lower }}
                        {% else %}
                            {{ question.verbose_type }}
                        {% endif %}
                        <span class="icon">
                            <i class="fas fa-angle-right"></i>
                        </span>
                    {% endspaceless %}
                </p>
            </div>
        </div>

        <div class="content">
            {% if show_answers_stats %}
                <p>
                    {% if question.user_answers_count == 0 %}
                        {% blocktrans %}
                            This question was <strong>never answered</strong>.
                        {% endblocktrans %}
                    {% else %}
                        {% blocktrans count count=question.user_answers_count %}
                            This question was <strong>answered once</strong>.
                        {% plural %}
                            This question was <strong>answered {{ count }} times</strong>.
                        {% endblocktrans %}
                    {% endif %}

                    {% if question.user_answers_count > 0 %}
                        {% if question.success_rate > 80 %}
                            {% blocktrans with success_rate=question.success_rate|floatformat:0 %}
                                That's a <strong class="has-text-success">{{ success_rate }}&nbsp;% success rate</strong>.
                            {% endblocktrans %}
                        {% elif question.success_rate > 50 %}
                            {% blocktrans with success_rate=question.success_rate|floatformat:0 %}
                                That's a <strong class="has-text-warning">{{ success_rate }}&nbsp;% success rate</strong>.
                            {% endblocktrans %}
                        {% else %}
                            {% blocktrans with success_rate=question.success_rate|floatformat:0 %}
                                That's a <strong class="has-text-danger">{{ success_rate }}&nbsp;% success rate</strong>.
                            {% endblocktrans %}
                        {% endif %}
                    {% endif %}
                </p>
            {% endif %}
            <div class="tags">
                {% if question.source %}
                    <span class="tag is-dark">{{ question.source }}</span>
                {% endif %}
                {% if question.difficulty == 1 %}<span class="tag is-success" title="{% trans "Easy difficulty" %}">{% trans "Easy" %}</span>
                {% elif question.difficulty == 2 %}<span class="tag is-warning" title="{% trans "Medium difficulty" %}">{% trans "Medium" %}</span>
                {% elif question.difficulty == 3 %}<span class="tag is-danger" title="{% trans "Hard difficulty" %}">{% trans "Hard" %}</span>{% endif %}
                {% for tag, omitted_children in question.reduced_tags.values %}
                    <a href=""
                       class="tag{% if forloop.counter > 3 %} is-overflowing-tag is-hidden{% endif %}"
                       title="{{ tag.get_ancestors|tree_path:" > " }} > {{ tag.name }}{% if omitted_children > 1 %} {% blocktrans count count=omitted_children %}+ one child{% plural %}+ {{ count }} children{% endblocktrans %}{% endif %}">
                        {{ tag.name }}
                    </a>
                    {% if forloop.last and forloop.counter > 3 %}
                        <a href="#"
                           class="tag is-overflowing-tags-toggler"
                           title="{% blocktrans count count=forloop.counter|sub:"3" %}Click to expand the other tag{% plural %}Click to expand the {{ count }} other tags{% endblocktrans %}"
                           data-other-title="{% blocktrans count count=forloop.counter|sub:"3" %}Click to retract the other tag{% plural %}Click to retract the {{ count }} other tags{% endblocktrans %}"
                           data-other-text="{% trans "«" %}">+ {{ forloop.counter|sub:"3" }}</a>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    <footer class="card-footer">
        <a href="#" class="card-footer-item is-unselectable has-text-grey has-text-centered" disabled>{% trans "View answers" %}</a>
        {% if perms.quizz.change_question %}
            <a href="{% url "quizz:management:questions-edit" pk=question.pk %}" class="card-footer-item has-text-centered">{% trans "Edit question" %}</a>
        {% endif %}
        {% if perms.quizz.delete_question %}
            <a href="{% url "quizz:management:questions-delete" pk=question.pk %}" class="card-footer-item has-text-centered">{% trans "Delete" %}</a>
        {% endif %}
    </footer>
</div>

quizz/templates/snippets/quizz-card.html
{% load i18n %}
{% load static %}

<div class="card">
    <div class="card-content">
        <div class="media">
            {% if management %}
                <div class="media-left">
                    <figure class="image is-48x48">
                        {% if quizz.user %}
                            <img src="{{ quizz.user.profile.picture.thumbnail.92x92 }}" alt="{{ quizz.user.get_full_name }}" class="is-rounded" />
                        {% else %}
                            <img src="{% static "images/user-default-picture.png" %}" alt="{{ quizz.user.get_full_name }}" class="is-rounded" />
                        {% endif %}
                    </figure>
                </div>
            {% endif %}
            <div class="media-content">
                <div class="columns is-vcentered">
                    <div class="column is-9">
                        {% if management %}
                            <p class="title is-4">
                                {% if quizz.user %}
                                    {{ quizz.user.get_full_name }}
                                {% else %}
                                    {% trans "Anonymous" %}
                                {% endif %}
                            </p>
                            <p class="subtitle is-6" title="{{ quizz.finished_at|date }} {{ quizz.finished_at|time }}{% if quizz.ip %} – {{ quizz.ip }}{% endif %}">
                                {% blocktrans with since=quizz.finished_at|timesince %}
                                    {{ since }} ago
                                {% endblocktrans %}
                                {% if not quizz.user %}
                                    – {% if quizz.ip %}{{ quizz.ip }}{% else %}{% trans "IP unknown or deleted" %}{% endif %}
                                {% endif %}
                            </p>
                        {% else %}
                            <p class="title is-5">
                                {% blocktrans with since=quizz.finished_at|timesince %}
                                    {{ since }} ago
                                {% endblocktrans %}
                            </p>
                            <p class="subtitle is-6">
                                {% blocktrans with date=quizz.finished_at|date hour=quizz.finished_at|time %}
                                    {{ date }} at {{ hour }}
                                {% endblocktrans %}
                            </p>
                        {% endif %}
                    </div>
                    <div class="column is-3 has-text-right is-hidden-mobile">
                        <span class="tag is-medium {% if quizz.score > 80 %}is-success{% elif quizz.score > 50 %}is-warning{% else %}is-danger{% endif %}">
                            {% blocktrans with score=quizz.score|floatformat:0 %}
                                {{ score }}&nbsp;%
                            {% endblocktrans %}
                        </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="content">
            <p>
                {% blocktrans with duration=quizz.started_at|timesince:quizz.finished_at count questions_count=quizz.questions_count  %}
                    <strong>{{ questions_count }} question</strong>, answered in {{ duration }}.
                {% plural %}
                    <strong>{{ questions_count }} questions</strong>, answered in {{ duration }}.
                {% endblocktrans %}
            </p>
            <div class="field is-grouped is-grouped-multiline">
                {% if quizz.perfect_answers > 0 %}
                    <div class="control">
                        <div class="tags has-addons">
                            {% blocktrans count count=quizz.perfect_answers %}
                                <span class="tag is-success">{{ count }}</span>
                                <span class="tag is-dark">perfect answer</span>
                            {% plural %}
                                <span class="tag is-success">{{ count }}</span>
                                <span class="tag is-dark">perfect answers</span>
                            {% endblocktrans %}
                        </div>
                    </div>
                {% endif %}
                {% if quizz.almost_answers > 0 %}
                    <div class="control">
                        <div class="tags has-addons">
                            {% blocktrans count count=quizz.almost_answers %}
                                <span class="tag is-warning">{{ count }}</span>
                                <span class="tag is-dark">close answer</span>
                            {% plural %}
                                <span class="tag is-warning">{{ count }}</span>
                                <span class="tag is-dark">close answers</span>
                            {% endblocktrans %}
                        </div>
                    </div>
                {% endif %}
                {% if quizz.failed_answers > 0 %}
                    <div class="control">
                        <div class="tags has-addons">
                            {% blocktrans count count=quizz.failed_answers %}
                                <span class="tag is-danger">{{ count }}</span>
                                <span class="tag is-dark">failed answer</span>
                            {% plural %}
                                <span class="tag is-danger">{{ count }}</span>
                                <span class="tag is-dark">failed answers</span>
                            {% endblocktrans %}
                        </div>
                    </div>
                {% endif %}
                <div class="control is-hidden-tablet">
                    <div class="tags has-addons">
                            <span class="tag {% if quizz.score > 80 %}is-success{% elif quizz.score > 50 %}is-warning{% else %}is-danger{% endif %}">{{ quizz.score|floatformat:0 }}&nbsp;%</span>
                            <span class="tag is-dark">{% trans "final score" %}</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer class="card-footer">
        <a href="{% url "quizz:quizz" slug=quizz.slug %}" class="card-footer-item has-text-centered-mobile">{% trans "Report" %}</a>
        {% if management and quizz.user != quizzes_user %}
            <a href="{% url "quizz:management:users-quizzes" username=quizz.user.username %}" class="card-footer-item has-text-centered-mobile">
                {% blocktrans with name=quizz.user.get_full_name %}
                    {{ name }}'s quizzes
                {% endblocktrans %}
            </a>
        {% endif %}
    </footer>
</div>